"""empty message

Revision ID: 125aa44b93d0
Revises: 375dc9e96660
Create Date: 2018-05-15 12:37:59.180585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125aa44b93d0'
down_revision = '375dc9e96660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
