"""empty message

Revision ID: 59995e5e4cc4
Revises: 125aa44b93d0
Create Date: 2018-05-18 08:43:10.259631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59995e5e4cc4'
down_revision = '125aa44b93d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET admin=False')
    op.alter_column('users', 'admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
